# Generated by Django 3.2.6 on 2021-08-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0003_alter_expense_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
