# Generated by Django 3.2.6 on 2021-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0005_auto_20210823_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Aman', max_length=72),
        ),
    ]
